[tool.poetry]
name = "ambient-clone"
version = "0.0.0"
description = ""
authors = ["uminus <ucon.ucon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
